name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    - gh-test
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        check-latest: true
    
    # Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
  
    # Set up Julia
    - uses: julia-actions/setup-julia@v2
      with:
        version: '1'

    # Build the book using make
    - name: Build the book
      run: make build

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
